import { I_ExtendedMappingSetFieldInput } from '@ferlab/next/lib/legacy/types';

const extendedMapping: I_ExtendedMappingSetFieldInput[] = [
  {
    field: 'age_at_recruitment',
    type: 'keyword',
    displayName: 'Age At Recruitment',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::age_at_recruitment',
  },
  {
    field: 'age_of_death',
    type: 'keyword',
    displayName: 'Age Of Death',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::age_of_death',
  },
  {
    field: 'biospecimens',
    type: 'nested',
    displayName: 'Biospecimens',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens',
  },
  {
    field: 'biospecimens.age_biospecimen_collection',
    type: 'keyword',
    displayName: 'Biospecimens Age Biospecimen Collection',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.age_biospecimen_collection',
  },
  {
    field: 'biospecimens.biospecimen_2_id',
    type: 'id',
    displayName: 'Biospecimens Biospecimen 2 Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.biospecimen_2_id',
  },
  {
    field: 'biospecimens.biospecimen_id',
    type: 'id',
    displayName: 'Biospecimens Biospecimen Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.biospecimen_id',
  },
  {
    field: 'biospecimens.biospecimen_tissue_source',
    type: 'keyword',
    displayName: 'Biospecimens Biospecimen Tissue Source',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.biospecimen_tissue_source',
  },
  {
    field: 'biospecimens.cancer_anatomic_location',
    type: 'object',
    displayName: 'Biospecimens Cancer Anatomic Location',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.cancer_anatomic_location',
  },
  {
    field: 'biospecimens.cancer_anatomic_location.code',
    type: 'keyword',
    displayName: 'Biospecimens Cancer Anatomic Location Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.cancer_anatomic_location.code',
  },
  {
    field: 'biospecimens.cancer_anatomic_location.display',
    type: 'keyword',
    displayName: 'Biospecimens Cancer Anatomic Location Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.cancer_anatomic_location.display',
  },
  {
    field: 'biospecimens.cancer_anatomic_location.text',
    type: 'keyword',
    displayName: 'Biospecimens Cancer Anatomic Location Text',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.cancer_anatomic_location.text',
  },
  {
    field: 'biospecimens.cancer_biospecimen_type',
    type: 'keyword',
    displayName: 'Biospecimens Cancer Biospecimen Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.cancer_biospecimen_type',
  },
  {
    field: 'biospecimens.sample_2_id',
    type: 'id',
    displayName: 'Biospecimens Sample 2 Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.sample_2_id',
  },
  {
    field: 'biospecimens.sample_id',
    type: 'id',
    displayName: 'Biospecimens Sample Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.sample_id',
  },
  {
    field: 'biospecimens.sample_type',
    type: 'keyword',
    displayName: 'Biospecimens Sample Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.sample_type',
  },
  {
    field: 'biospecimens.submitter_biospecimen_id',
    type: 'id',
    displayName: 'Biospecimens Submitter Biospecimen Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.submitter_biospecimen_id',
  },
  {
    field: 'biospecimens.submitter_sample_id',
    type: 'id',
    displayName: 'Biospecimens Submitter Sample Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.submitter_sample_id',
  },
  {
    field: 'biospecimens.tumor_histological_type',
    type: 'object',
    displayName: 'Biospecimens Tumor Histological Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.tumor_histological_type',
  },
  {
    field: 'biospecimens.tumor_histological_type.code',
    type: 'keyword',
    displayName: 'Biospecimens Tumor Histological Type Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.tumor_histological_type.code',
  },
  {
    field: 'biospecimens.tumor_histological_type.display',
    type: 'keyword',
    displayName: 'Biospecimens Tumor Histological Type Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.tumor_histological_type.display',
  },
  {
    field: 'biospecimens.tumor_histological_type.text',
    type: 'keyword',
    displayName: 'Biospecimens Tumor Histological Type Text',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.tumor_histological_type.text',
  },
  {
    field: 'biospecimens.tumor_normal_designation',
    type: 'keyword',
    displayName: 'Biospecimens Tumor Normal Designation',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::biospecimens.tumor_normal_designation',
  },
  {
    field: 'cause_of_death',
    type: 'keyword',
    displayName: 'Cause Of Death',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::cause_of_death',
  },
  {
    field: 'diagnoses',
    type: 'nested',
    displayName: 'Diagnoses',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::diagnoses',
  },
  {
    field: 'diagnoses.age_at_diagnosis',
    type: 'keyword',
    displayName: 'Diagnoses Age At Diagnosis',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::diagnoses.age_at_diagnosis',
  },
  {
    field: 'diagnoses.diagnosis_ICD_code',
    type: 'keyword',
    displayName: 'Diagnoses Diagnosis ICD Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::diagnoses.diagnosis_ICD_code',
  },
  {
    field: 'diagnoses.diagnosis_icd_display',
    type: 'keyword',
    displayName: 'Diagnoses Diagnosis Icd Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::diagnoses.diagnosis_icd_display',
  },
  {
    field: 'diagnoses.diagnosis_mondo_code',
    type: 'keyword',
    displayName: 'Diagnoses Diagnosis Mondo Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::diagnoses.diagnosis_mondo_code',
  },
  {
    field: 'diagnoses.diagnosis_mondo_display',
    type: 'keyword',
    displayName: 'Diagnoses Diagnosis Mondo Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::diagnoses.diagnosis_mondo_display',
  },
  {
    field: 'diagnoses.diagnosis_source_text',
    type: 'keyword',
    displayName: 'Diagnoses Diagnosis Source Text',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::diagnoses.diagnosis_source_text',
  },
  {
    field: 'diagnoses.fhir_id',
    type: 'id',
    displayName: 'Diagnoses Fhir Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::diagnoses.fhir_id',
  },
  {
    field: 'ethnicity',
    type: 'keyword',
    displayName: 'Ethnicity',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::ethnicity',
  },
  {
    field: 'family_id',
    type: 'id',
    displayName: 'Family Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::family_id',
  },
  {
    field: 'family_relationships',
    type: 'nested',
    displayName: 'Family Relationships',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::family_relationships',
  },
  {
    field: 'family_relationships.family_id',
    type: 'id',
    displayName: 'Family Relationships Family Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::family_relationships.family_id',
  },
  {
    field: 'family_relationships.family_type',
    type: 'keyword',
    displayName: 'Family Relationships Family Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::family_relationships.family_type',
  },
  {
    field: 'family_relationships.focus_participant_id',
    type: 'id',
    displayName: 'Family Relationships Focus Participant Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::family_relationships.focus_participant_id',
  },
  {
    field: 'family_relationships.is_affected',
    type: 'keyword',
    displayName: 'Family Relationships Is Affected',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::family_relationships.is_affected',
  },
  {
    field: 'family_relationships.participant_id',
    type: 'id',
    displayName: 'Family Relationships Participant Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::family_relationships.participant_id',
  },
  {
    field: 'family_relationships.relationship_to_proband',
    type: 'keyword',
    displayName: 'Family Relationships Relationship To Proband',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::family_relationships.relationship_to_proband',
  },
  {
    field: 'family_relationships.submitter_family_id',
    type: 'id',
    displayName: 'Family Relationships Submitter Family Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::family_relationships.submitter_family_id',
  },
  {
    field: 'family_relationships.submitter_participant_id',
    type: 'id',
    displayName: 'Family Relationships Submitter Participant Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::family_relationships.submitter_participant_id',
  },
  {
    field: 'family_type',
    type: 'keyword',
    displayName: 'Family Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::family_type',
  },
  {
    field: 'files',
    type: 'nested',
    displayName: 'Files',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files',
  },
  {
    field: 'files.biospecimen_reference',
    type: 'keyword',
    displayName: 'Files Biospecimen Reference',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimen_reference',
  },
  {
    field: 'files.biospecimens',
    type: 'nested',
    displayName: 'Files Biospecimens',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens',
  },
  {
    field: 'files.biospecimens.age_biospecimen_collection',
    type: 'keyword',
    displayName: 'Files Biospecimens Age Biospecimen Collection',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.age_biospecimen_collection',
  },
  {
    field: 'files.biospecimens.biospecimen_2_id',
    type: 'id',
    displayName: 'Files Biospecimens Biospecimen 2 Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.biospecimen_2_id',
  },
  {
    field: 'files.biospecimens.biospecimen_id',
    type: 'id',
    displayName: 'Files Biospecimens Biospecimen Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.biospecimen_id',
  },
  {
    field: 'files.biospecimens.biospecimen_tissue_source',
    type: 'keyword',
    displayName: 'Files Biospecimens Biospecimen Tissue Source',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.biospecimen_tissue_source',
  },
  {
    field: 'files.biospecimens.cancer_anatomic_location',
    type: 'object',
    displayName: 'Files Biospecimens Cancer Anatomic Location',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.cancer_anatomic_location',
  },
  {
    field: 'files.biospecimens.cancer_anatomic_location.code',
    type: 'text',
    displayName: 'Files Biospecimens Cancer Anatomic Location Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.cancer_anatomic_location.code',
  },
  {
    field: 'files.biospecimens.cancer_anatomic_location.display',
    type: 'text',
    displayName: 'Files Biospecimens Cancer Anatomic Location Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.cancer_anatomic_location.display',
  },
  {
    field: 'files.biospecimens.cancer_anatomic_location.text',
    type: 'text',
    displayName: 'Files Biospecimens Cancer Anatomic Location Text',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.cancer_anatomic_location.text',
  },
  {
    field: 'files.biospecimens.cancer_biospecimen_type',
    type: 'text',
    displayName: 'Files Biospecimens Cancer Biospecimen Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.cancer_biospecimen_type',
  },
  {
    field: 'files.biospecimens.sample_2_id',
    type: 'id',
    displayName: 'Files Biospecimens Sample 2 Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.sample_2_id',
  },
  {
    field: 'files.biospecimens.sample_id',
    type: 'id',
    displayName: 'Files Biospecimens Sample Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.sample_id',
  },
  {
    field: 'files.biospecimens.sample_type',
    type: 'keyword',
    displayName: 'Files Biospecimens Sample Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.sample_type',
  },
  {
    field: 'files.biospecimens.submitter_biospecimen_id',
    type: 'id',
    displayName: 'Files Biospecimens Submitter Biospecimen Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.submitter_biospecimen_id',
  },
  {
    field: 'files.biospecimens.submitter_sample_id',
    type: 'id',
    displayName: 'Files Biospecimens Submitter Sample Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.submitter_sample_id',
  },
  {
    field: 'files.biospecimens.tumor_histological_type',
    type: 'object',
    displayName: 'Files Biospecimens Tumor Histological Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.tumor_histological_type',
  },
  {
    field: 'files.biospecimens.tumor_histological_type.code',
    type: 'text',
    displayName: 'Files Biospecimens Tumor Histological Type Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.tumor_histological_type.code',
  },
  {
    field: 'files.biospecimens.tumor_histological_type.display',
    type: 'text',
    displayName: 'Files Biospecimens Tumor Histological Type Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.tumor_histological_type.display',
  },
  {
    field: 'files.biospecimens.tumor_histological_type.text',
    type: 'text',
    displayName: 'Files Biospecimens Tumor Histological Type Text',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.tumor_histological_type.text',
  },
  {
    field: 'files.biospecimens.tumor_normal_designation',
    type: 'text',
    displayName: 'Files Biospecimens Tumor Normal Designation',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.biospecimens.tumor_normal_designation',
  },
  {
    field: 'files.data_category',
    type: 'keyword',
    displayName: 'Files Data Category',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.data_category',
  },
  {
    field: 'files.data_type',
    type: 'keyword',
    displayName: 'Files Data Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.data_type',
  },
  {
    field: 'files.dataset',
    type: 'keyword',
    displayName: 'Files Dataset',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.dataset',
  },
  {
    field: 'files.ferload_url',
    type: 'keyword',
    displayName: 'Files Ferload Url',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.ferload_url',
  },
  {
    field: 'files.file_2_id',
    type: 'id',
    displayName: 'Files File 2 Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.file_2_id',
  },
  {
    field: 'files.file_format',
    type: 'keyword',
    displayName: 'Files File Format',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.file_format',
  },
  {
    field: 'files.file_hash',
    type: 'keyword',
    displayName: 'Files File Hash',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.file_hash',
  },
  {
    field: 'files.file_id',
    type: 'id',
    displayName: 'Files File Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.file_id',
  },
  {
    field: 'files.file_name',
    type: 'keyword',
    displayName: 'Files File Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.file_name',
  },
  {
    field: 'files.file_size',
    type: 'keyword',
    displayName: 'Files File Size',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.file_size',
  },
  {
    field: 'files.relates_to',
    type: 'keyword',
    displayName: 'Files Relates To',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.relates_to',
  },
  {
    field: 'files.sample',
    type: 'object',
    displayName: 'Files Sample',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sample',
  },
  {
    field: 'files.sample.lab_aliquot_ids',
    type: 'id',
    displayName: 'Files Sample Lab Aliquot Ids',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sample.lab_aliquot_ids',
  },
  {
    field: 'files.sample.ldm_sample_id',
    type: 'id',
    displayName: 'Files Sample Ldm Sample Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sample.ldm_sample_id',
  },
  {
    field: 'files.sequencing_experiment',
    type: 'object',
    displayName: 'Files Sequencing Experiment',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment',
  },
  {
    field: 'files.sequencing_experiment.analysis_files',
    type: 'object',
    displayName: 'Files Sequencing Experiment Analysis Files',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.analysis_files',
  },
  {
    field: 'files.sequencing_experiment.analysis_files.data_type',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Analysis Files Data Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.analysis_files.data_type',
  },
  {
    field: 'files.sequencing_experiment.analysis_files.file_id',
    type: 'id',
    displayName: 'Files Sequencing Experiment Analysis Files File Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.analysis_files.file_id',
  },
  {
    field: 'files.sequencing_experiment.analysis_id',
    type: 'id',
    displayName: 'Files Sequencing Experiment Analysis Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.analysis_id',
  },
  {
    field: 'files.sequencing_experiment.bio_informatic_analysis',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Bio Informatic Analysis',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.bio_informatic_analysis',
  },
  {
    field: 'files.sequencing_experiment.capture_kit',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Capture Kit',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.capture_kit',
  },
  {
    field: 'files.sequencing_experiment.experimental_strategy',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Experimental Strategy',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.experimental_strategy',
  },
  {
    field: 'files.sequencing_experiment.experimental_strategy_1',
    type: 'object',
    displayName: 'Files Sequencing Experiment Experimental Strategy 1',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.experimental_strategy_1',
  },
  {
    field: 'files.sequencing_experiment.experimental_strategy_1.code',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Experimental Strategy 1 Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.experimental_strategy_1.code',
  },
  {
    field: 'files.sequencing_experiment.experimental_strategy_1.display',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Experimental Strategy 1 Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.experimental_strategy_1.display',
  },
  {
    field: 'files.sequencing_experiment.genome_build',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Genome Build',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.genome_build',
  },
  {
    field: 'files.sequencing_experiment.labAliquotID',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Lab Aliquot ID',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.labAliquotID',
  },
  {
    field: 'files.sequencing_experiment.owner',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Owner',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.owner',
  },
  {
    field: 'files.sequencing_experiment.pipeline',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Pipeline',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.pipeline',
  },
  {
    field: 'files.sequencing_experiment.platform',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Platform',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.platform',
  },
  {
    field: 'files.sequencing_experiment.protocol',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Protocol',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.protocol',
  },
  {
    field: 'files.sequencing_experiment.read_length',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Read Length',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.read_length',
  },
  {
    field: 'files.sequencing_experiment.run_alias',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Run Alias',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.run_alias',
  },
  {
    field: 'files.sequencing_experiment.run_date',
    type: 'date',
    displayName: 'Files Sequencing Experiment Run Date',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.run_date',
  },
  {
    field: 'files.sequencing_experiment.run_dates',
    type: 'date',
    displayName: 'Files Sequencing Experiment Run Dates',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.run_dates',
  },
  {
    field: 'files.sequencing_experiment.run_ids',
    type: 'id',
    displayName: 'Files Sequencing Experiment Run Ids',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.run_ids',
  },
  {
    field: 'files.sequencing_experiment.run_name',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Run Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.run_name',
  },
  {
    field: 'files.sequencing_experiment.selection',
    type: 'object',
    displayName: 'Files Sequencing Experiment Selection',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.selection',
  },
  {
    field: 'files.sequencing_experiment.selection.code',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Selection Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.selection.code',
  },
  {
    field: 'files.sequencing_experiment.selection.display',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Selection Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.selection.display',
  },
  {
    field: 'files.sequencing_experiment.sequencer_id',
    type: 'id',
    displayName: 'Files Sequencing Experiment Sequencer Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.sequencer_id',
  },
  {
    field: 'files.sequencing_experiment.source',
    type: 'object',
    displayName: 'Files Sequencing Experiment Source',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.source',
  },
  {
    field: 'files.sequencing_experiment.source.code',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Source Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.source.code',
  },
  {
    field: 'files.sequencing_experiment.source.display',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Source Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.source.display',
  },
  {
    field: 'files.sequencing_experiment.target_capture_kit',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Target Capture Kit',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.target_capture_kit',
  },
  {
    field: 'files.sequencing_experiment.target_loci',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Target Loci',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.target_loci',
  },
  {
    field: 'files.sequencing_experiment.type_of_sequencing',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Type Of Sequencing',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.type_of_sequencing',
  },
  {
    field: 'files.sequencing_experiment.workflow_name',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Workflow Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.workflow_name',
  },
  {
    field: 'files.sequencing_experiment.workflow_version',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Workflow Version',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.workflow_version',
  },
  {
    field: 'files.study_id',
    type: 'id',
    displayName: 'Files Study Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::files.study_id',
  },
  {
    field: 'gender',
    type: 'object',
    displayName: 'Gender',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::gender',
  },
  {
    field: 'gender.another_category',
    type: 'keyword',
    displayName: 'Gender Another Category',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::gender.another_category',
  },
  {
    field: 'gender.code',
    type: 'keyword',
    displayName: 'Gender Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::gender.code',
  },
  {
    field: 'gender.collect_method',
    type: 'object',
    displayName: 'Gender Collect Method',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::gender.collect_method',
  },
  {
    field: 'gender.collect_method.code',
    type: 'keyword',
    displayName: 'Gender Collect Method Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::gender.collect_method.code',
  },
  {
    field: 'gender.collect_method.display',
    type: 'keyword',
    displayName: 'Gender Collect Method Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::gender.collect_method.display',
  },
  {
    field: 'gender.display',
    type: 'keyword',
    displayName: 'Gender Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::gender.display',
  },
  {
    field: 'icd_tagged',
    type: 'nested',
    displayName: 'Icd Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::icd_tagged',
  },
  {
    field: 'icd_tagged.age_at_event',
    type: 'keyword',
    displayName: 'Icd Tagged Age At Event',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::icd_tagged.age_at_event',
  },
  {
    field: 'icd_tagged.internal_phenotype_id',
    type: 'id',
    displayName: 'Icd Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::icd_tagged.internal_phenotype_id',
  },
  {
    field: 'icd_tagged.is_leaf',
    type: 'boolean',
    displayName: 'Icd Tagged Is Leaf',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::icd_tagged.is_leaf',
  },
  {
    field: 'icd_tagged.is_tagged',
    type: 'boolean',
    displayName: 'Icd Tagged Is Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::icd_tagged.is_tagged',
  },
  {
    field: 'icd_tagged.name',
    type: 'keyword',
    displayName: 'Icd Tagged Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::icd_tagged.name',
  },
  {
    field: 'icd_tagged.parents',
    type: 'keyword',
    displayName: 'Icd Tagged Parents',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::icd_tagged.parents',
  },
  {
    field: 'icd_tagged.source_text',
    type: 'keyword',
    displayName: 'Icd Tagged Source Text',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::icd_tagged.source_text',
  },
  {
    field: 'is_a_proband',
    type: 'boolean',
    displayName: 'Is A Proband',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::is_a_proband',
  },
  {
    field: 'is_affected',
    type: 'keyword',
    displayName: 'Is Affected',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::is_affected',
  },
  {
    field: 'mondo',
    type: 'nested',
    displayName: 'Mondo',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::mondo',
  },
  {
    field: 'mondo.age_at_event',
    type: 'keyword',
    displayName: 'Mondo Age At Event',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::mondo.age_at_event',
  },
  {
    field: 'mondo.is_leaf',
    type: 'boolean',
    displayName: 'Mondo Is Leaf',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::mondo.is_leaf',
  },
  {
    field: 'mondo.is_tagged',
    type: 'boolean',
    displayName: 'Mondo Is Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::mondo.is_tagged',
  },
  {
    field: 'mondo.name',
    type: 'keyword',
    displayName: 'Mondo Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::mondo.name',
  },
  {
    field: 'mondo.parents',
    type: 'keyword',
    displayName: 'Mondo Parents',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::mondo.parents',
  },
  {
    field: 'mondo_tagged',
    type: 'nested',
    displayName: 'Mondo Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::mondo_tagged',
  },
  {
    field: 'mondo_tagged.age_at_event',
    type: 'keyword',
    displayName: 'Mondo Tagged Age At Event',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::mondo_tagged.age_at_event',
  },
  {
    field: 'mondo_tagged.internal_phenotype_id',
    type: 'id',
    displayName: 'Mondo Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::mondo_tagged.internal_phenotype_id',
  },
  {
    field: 'mondo_tagged.is_leaf',
    type: 'boolean',
    displayName: 'Mondo Tagged Is Leaf',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::mondo_tagged.is_leaf',
  },
  {
    field: 'mondo_tagged.is_tagged',
    type: 'boolean',
    displayName: 'Mondo Tagged Is Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::mondo_tagged.is_tagged',
  },
  {
    field: 'mondo_tagged.name',
    type: 'keyword',
    displayName: 'Mondo Tagged Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::mondo_tagged.name',
  },
  {
    field: 'mondo_tagged.parents',
    type: 'keyword',
    displayName: 'Mondo Tagged Parents',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::mondo_tagged.parents',
  },
  {
    field: 'mondo_tagged.source_text',
    type: 'keyword',
    displayName: 'Mondo Tagged Source Text',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::mondo_tagged.source_text',
  },
  {
    field: 'observed_phenotype_tagged',
    type: 'nested',
    displayName: 'Observed Phenotype Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged',
  },
  {
    field: 'observed_phenotype_tagged.age_at_event',
    type: 'keyword',
    displayName: 'Observed Phenotype Tagged Age At Event',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged.age_at_event',
  },
  {
    field: 'observed_phenotype_tagged.internal_phenotype_id',
    type: 'id',
    displayName: 'Observed Phenotype Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged.internal_phenotype_id',
  },
  {
    field: 'observed_phenotype_tagged.is_leaf',
    type: 'boolean',
    displayName: 'Observed Phenotype Tagged Is Leaf',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged.is_leaf',
  },
  {
    field: 'observed_phenotype_tagged.is_tagged',
    type: 'boolean',
    displayName: 'Observed Phenotype Tagged Is Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged.is_tagged',
  },
  {
    field: 'observed_phenotype_tagged.name',
    type: 'keyword',
    displayName: 'Observed Phenotype Tagged Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged.name',
  },
  {
    field: 'observed_phenotype_tagged.parents',
    type: 'keyword',
    displayName: 'Observed Phenotype Tagged Parents',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged.parents',
  },
  {
    field: 'observed_phenotype_tagged.source_text',
    type: 'keyword',
    displayName: 'Observed Phenotype Tagged Source Text',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged.source_text',
  },
  {
    field: 'observed_phenotypes',
    type: 'nested',
    displayName: 'Observed Phenotypes',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::observed_phenotypes',
  },
  {
    field: 'observed_phenotypes.age_at_event',
    type: 'keyword',
    displayName: 'Observed Phenotypes Age At Event',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::observed_phenotypes.age_at_event',
  },
  {
    field: 'observed_phenotypes.is_leaf',
    type: 'boolean',
    displayName: 'Observed Phenotypes Is Leaf',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::observed_phenotypes.is_leaf',
  },
  {
    field: 'observed_phenotypes.is_tagged',
    type: 'boolean',
    displayName: 'Observed Phenotypes Is Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::observed_phenotypes.is_tagged',
  },
  {
    field: 'observed_phenotypes.name',
    type: 'keyword',
    displayName: 'Observed Phenotypes Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::observed_phenotypes.name',
  },
  {
    field: 'observed_phenotypes.parents',
    type: 'keyword',
    displayName: 'Observed Phenotypes Parents',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::observed_phenotypes.parents',
  },
  {
    field: 'participant_2_id',
    type: 'id',
    displayName: 'Participant 2 Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::participant_2_id',
  },
  {
    field: 'participant_id',
    type: 'id',
    displayName: 'Participant Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::participant_id',
  },
  {
    field: 'phenotypes_tagged',
    type: 'nested',
    displayName: 'Phenotypes Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged',
  },
  {
    field: 'phenotypes_tagged.age_at_event',
    type: 'keyword',
    displayName: 'Phenotypes Tagged Age At Event',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.age_at_event',
  },
  {
    field: 'phenotypes_tagged.internal_phenotype_id',
    type: 'id',
    displayName: 'Phenotypes Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.internal_phenotype_id',
  },
  {
    field: 'phenotypes_tagged.is_leaf',
    type: 'boolean',
    displayName: 'Phenotypes Tagged Is Leaf',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.is_leaf',
  },
  {
    field: 'phenotypes_tagged.is_observed',
    type: 'boolean',
    displayName: 'Phenotypes Tagged Is Observed',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.is_observed',
  },
  {
    field: 'phenotypes_tagged.is_tagged',
    type: 'boolean',
    displayName: 'Phenotypes Tagged Is Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.is_tagged',
  },
  {
    field: 'phenotypes_tagged.name',
    type: 'keyword',
    displayName: 'Phenotypes Tagged Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.name',
  },
  {
    field: 'phenotypes_tagged.parents',
    type: 'keyword',
    displayName: 'Phenotypes Tagged Parents',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.parents',
  },
  {
    field: 'phenotypes_tagged.source_text',
    type: 'keyword',
    displayName: 'Phenotypes Tagged Source Text',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.source_text',
  },
  {
    field: 'race',
    type: 'object',
    displayName: 'Race',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::race',
  },
  {
    field: 'race.another_category',
    type: 'keyword',
    displayName: 'Race Another Category',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::race.another_category',
  },
  {
    field: 'race.code',
    type: 'keyword',
    displayName: 'Race Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::race.code',
  },
  {
    field: 'race.collect_method',
    type: 'object',
    displayName: 'Race Collect Method',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::race.collect_method',
  },
  {
    field: 'race.collect_method.code',
    type: 'keyword',
    displayName: 'Race Collect Method Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::race.collect_method.code',
  },
  {
    field: 'race.collect_method.display',
    type: 'keyword',
    displayName: 'Race Collect Method Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::race.collect_method.display',
  },
  {
    field: 'race.display',
    type: 'keyword',
    displayName: 'Race Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::race.display',
  },
  {
    field: 'relationship_to_proband',
    type: 'keyword',
    displayName: 'Relationship To Proband',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::relationship_to_proband',
  },
  {
    field: 'security',
    type: 'keyword',
    displayName: 'Security',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::security',
  },
  {
    field: 'sex',
    type: 'keyword',
    displayName: 'Sex',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::sex',
  },
  {
    field: 'sex_at_birth',
    type: 'object',
    displayName: 'Sex At Birth',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::sex_at_birth',
  },
  {
    field: 'sex_at_birth.another_category',
    type: 'keyword',
    displayName: 'Sex At Birth Another Category',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::sex_at_birth.another_category',
  },
  {
    field: 'sex_at_birth.code',
    type: 'keyword',
    displayName: 'Sex At Birth Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::sex_at_birth.code',
  },
  {
    field: 'sex_at_birth.collect_method',
    type: 'object',
    displayName: 'Sex At Birth Collect Method',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::sex_at_birth.collect_method',
  },
  {
    field: 'sex_at_birth.collect_method.code',
    type: 'keyword',
    displayName: 'Sex At Birth Collect Method Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::sex_at_birth.collect_method.code',
  },
  {
    field: 'sex_at_birth.collect_method.display',
    type: 'keyword',
    displayName: 'Sex At Birth Collect Method Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::sex_at_birth.collect_method.display',
  },
  {
    field: 'sex_at_birth.display',
    type: 'keyword',
    displayName: 'Sex At Birth Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::sex_at_birth.display',
  },
  {
    field: 'study',
    type: 'object',
    displayName: 'Study',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study',
  },
  {
    field: 'study.access_authority',
    type: 'object',
    displayName: 'Study Access Authority',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study.access_authority',
  },
  {
    field: 'study.access_authority.type',
    type: 'keyword',
    displayName: 'Study Access Authority Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study.access_authority.type',
  },
  {
    field: 'study.access_authority.value',
    type: 'keyword',
    displayName: 'Study Access Authority Value',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study.access_authority.value',
  },
  {
    field: 'study.data_access_codes',
    type: 'object',
    displayName: 'Study Data Access Codes',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study.data_access_codes',
  },
  {
    field: 'study.data_access_codes.access_limitations',
    type: 'keyword',
    displayName: 'Study Data Access Codes Access Limitations',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study.data_access_codes.access_limitations',
  },
  {
    field: 'study.data_access_codes.access_requirements',
    type: 'keyword',
    displayName: 'Study Data Access Codes Access Requirements',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study.data_access_codes.access_requirements',
  },
  {
    field: 'study.domain',
    type: 'keyword',
    displayName: 'Study Domain',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study.domain',
  },
  {
    field: 'study.name',
    type: 'keyword',
    displayName: 'Study Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study.name',
  },
  {
    field: 'study.population',
    type: 'keyword',
    displayName: 'Study Population',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study.population',
  },
  {
    field: 'study.programs',
    type: 'nested',
    displayName: 'Study Programs',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study.programs',
  },
  {
    field: 'study.programs.name_en',
    type: 'keyword',
    displayName: 'Study Programs Name En',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study.programs.name_en',
  },
  {
    field: 'study.programs.name_fr',
    type: 'keyword',
    displayName: 'Study Programs Name Fr',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study.programs.name_fr',
  },
  {
    field: 'study.programs.program_id',
    type: 'id',
    displayName: 'Study Programs Program Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study.programs.program_id',
  },
  {
    field: 'study.study_code',
    type: 'keyword',
    displayName: 'Study Study Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study.study_code',
  },
  {
    field: 'study_code',
    type: 'keyword',
    displayName: 'Study Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study_code',
  },
  {
    field: 'study_id',
    type: 'id',
    displayName: 'Study Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::study_id',
  },
  {
    field: 'submitter_participant_id',
    type: 'id',
    displayName: 'Submitter Participant Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::submitter_participant_id',
  },
  {
    field: 'vital_status',
    type: 'keyword',
    displayName: 'Vital Status',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Participant::extended::vital_status',
  },
];

export default extendedMapping;
