import { I_ExtendedMappingSetFieldInput } from '@ferlab/next/lib/legacy/types';

const extendedMapping: I_ExtendedMappingSetFieldInput[] = [
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'age_at_recruitment',
    displayName: 'Age At Recruitment',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::age_at_recruitment',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'age_of_death',
    displayName: 'Age Of Death',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::age_of_death',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'biospecimens',
    displayName: 'Biospecimens',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Participant::extended::biospecimens',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'biospecimens.age_biospecimen_collection',
    displayName: 'Biospecimens Age Biospecimen Collection',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::biospecimens.age_biospecimen_collection',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'biospecimens.biospecimen_2_id',
    displayName: 'Biospecimens Biospecimen 2 Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::biospecimens.biospecimen_2_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'biospecimens.biospecimen_id',
    displayName: 'Biospecimens Biospecimen Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::biospecimens.biospecimen_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'biospecimens.biospecimen_tissue_source',
    displayName: 'Biospecimens Biospecimen Tissue Source',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::biospecimens.biospecimen_tissue_source',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'biospecimens.sample_2_id',
    displayName: 'Biospecimens Sample 2 Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::biospecimens.sample_2_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'biospecimens.sample_id',
    displayName: 'Biospecimens Sample Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::biospecimens.sample_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'biospecimens.sample_type',
    displayName: 'Biospecimens Sample Type',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::biospecimens.sample_type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'biospecimens.submitter_biospecimen_id',
    displayName: 'Biospecimens Submitter Biospecimen Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::biospecimens.submitter_biospecimen_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'biospecimens.submitter_sample_id',
    displayName: 'Biospecimens Submitter Sample Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::biospecimens.submitter_sample_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'cause_of_death',
    displayName: 'Cause Of Death',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::cause_of_death',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'deceasedBoolean',
    displayName: 'Deceased Boolean',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::deceasedBoolean',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'diagnoses',
    displayName: 'Diagnoses',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Participant::extended::diagnoses',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'diagnoses.age_at_diagnosis',
    displayName: 'Diagnoses Age At Diagnosis',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::diagnoses.age_at_diagnosis',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'diagnoses.diagnosis_ICD_code',
    displayName: 'Diagnoses Diagnosis ICD Code',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::diagnoses.diagnosis_ICD_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'diagnoses.diagnosis_icd_display',
    displayName: 'Diagnoses Diagnosis Icd Display',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::diagnoses.diagnosis_icd_display',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'diagnoses.diagnosis_mondo_code',
    displayName: 'Diagnoses Diagnosis Mondo Code',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::diagnoses.diagnosis_mondo_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'diagnoses.diagnosis_mondo_display',
    displayName: 'Diagnoses Diagnosis Mondo Display',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::diagnoses.diagnosis_mondo_display',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'diagnoses.diagnosis_source_text',
    displayName: 'Diagnoses Diagnosis Source Text',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::diagnoses.diagnosis_source_text',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'diagnoses.fhir_id',
    displayName: 'Diagnoses Fhir Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::diagnoses.fhir_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'ethnicity',
    displayName: 'Ethnicity',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::ethnicity',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'family_id',
    displayName: 'Family Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::family_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'family_relationships',
    displayName: 'Family Relationships',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Participant::extended::family_relationships',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'family_relationships.family_id',
    displayName: 'Family Relationships Family Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::family_relationships.family_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'family_relationships.family_type',
    displayName: 'Family Relationships Family Type',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::family_relationships.family_type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'family_relationships.focus_participant_id',
    displayName: 'Family Relationships Focus Participant Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::family_relationships.focus_participant_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'family_relationships.is_affected',
    displayName: 'Family Relationships Is Affected',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::family_relationships.is_affected',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'family_relationships.participant_id',
    displayName: 'Family Relationships Participant Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::family_relationships.participant_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'family_relationships.relationship_to_proband',
    displayName: 'Family Relationships Relationship To Proband',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::family_relationships.relationship_to_proband',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'family_relationships.submitter_family_id',
    displayName: 'Family Relationships Submitter Family Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::family_relationships.submitter_family_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'family_relationships.submitter_participant_id',
    displayName: 'Family Relationships Submitter Participant Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::family_relationships.submitter_participant_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'family_type',
    displayName: 'Family Type',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::family_type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files',
    displayName: 'Files',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Participant::extended::files',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.biospecimen_reference',
    displayName: 'Files Biospecimen Reference',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.biospecimen_reference',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.biospecimens',
    displayName: 'Files Biospecimens',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Participant::extended::files.biospecimens',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.biospecimens.age_biospecimen_collection',
    displayName: 'Files Biospecimens Age Biospecimen Collection',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.biospecimens.age_biospecimen_collection',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.biospecimens.biospecimen_2_id',
    displayName: 'Files Biospecimens Biospecimen 2 Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::files.biospecimens.biospecimen_2_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.biospecimens.biospecimen_id',
    displayName: 'Files Biospecimens Biospecimen Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::files.biospecimens.biospecimen_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.biospecimens.biospecimen_tissue_source',
    displayName: 'Files Biospecimens Biospecimen Tissue Source',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.biospecimens.biospecimen_tissue_source',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.biospecimens.sample_2_id',
    displayName: 'Files Biospecimens Sample 2 Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::files.biospecimens.sample_2_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.biospecimens.sample_id',
    displayName: 'Files Biospecimens Sample Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::files.biospecimens.sample_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.biospecimens.sample_type',
    displayName: 'Files Biospecimens Sample Type',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.biospecimens.sample_type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.biospecimens.submitter_biospecimen_id',
    displayName: 'Files Biospecimens Submitter Biospecimen Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::files.biospecimens.submitter_biospecimen_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.biospecimens.submitter_sample_id',
    displayName: 'Files Biospecimens Submitter Sample Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::files.biospecimens.submitter_sample_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.data_category',
    displayName: 'Files Data Category',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.data_category',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.data_type',
    displayName: 'Files Data Type',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.data_type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.dataset',
    displayName: 'Files Dataset',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.dataset',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.ferload_url',
    displayName: 'Files Ferload Url',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.ferload_url',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.file_2_id',
    displayName: 'Files File 2 Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::files.file_2_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.file_format',
    displayName: 'Files File Format',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.file_format',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.file_hash',
    displayName: 'Files File Hash',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.file_hash',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.file_id',
    displayName: 'Files File Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::files.file_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.file_name',
    displayName: 'Files File Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.file_name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.file_size',
    displayName: 'Files File Size',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.file_size',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.relates_to',
    displayName: 'Files Relates To',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.relates_to',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.release_id',
    displayName: 'Files Release Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::files.release_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment',
    displayName: 'Files Sequencing Experiment',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.alir',
    displayName: 'Files Sequencing Experiment Alir',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.alir',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.analysis_id',
    displayName: 'Files Sequencing Experiment Analysis Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.analysis_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.bio_informatic_analysis',
    displayName: 'Files Sequencing Experiment Bio Informatic Analysis',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.bio_informatic_analysis',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.capture_kit',
    displayName: 'Files Sequencing Experiment Capture Kit',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.capture_kit',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.experimental_strategy',
    displayName: 'Files Sequencing Experiment Experimental Strategy',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.experimental_strategy',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.gcnv',
    displayName: 'Files Sequencing Experiment Gcnv',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.gcnv',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.genome_build',
    displayName: 'Files Sequencing Experiment Genome Build',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.genome_build',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.gsv',
    displayName: 'Files Sequencing Experiment Gsv',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.gsv',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.labAliquotID',
    displayName: 'Files Sequencing Experiment Lab Aliquot ID',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.labAliquotID',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.ldm_sample_id',
    displayName: 'Files Sequencing Experiment Ldm Sample Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.ldm_sample_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.owner',
    displayName: 'Files Sequencing Experiment Owner',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.owner',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.platform',
    displayName: 'Files Sequencing Experiment Platform',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.platform',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.read_length',
    displayName: 'Files Sequencing Experiment Read Length',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.read_length',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.run_alias',
    displayName: 'Files Sequencing Experiment Run Alias',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.run_alias',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.run_date',
    displayName: 'Files Sequencing Experiment Run Date',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'date',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.run_date',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.run_name',
    displayName: 'Files Sequencing Experiment Run Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.run_name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.sequencer_id',
    displayName: 'Files Sequencing Experiment Sequencer Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.sequencer_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.snv',
    displayName: 'Files Sequencing Experiment Snv',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.snv',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.ssup',
    displayName: 'Files Sequencing Experiment Ssup',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.ssup',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.type_of_sequencing',
    displayName: 'Files Sequencing Experiment Type Of Sequencing',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.type_of_sequencing',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.workflow_name',
    displayName: 'Files Sequencing Experiment Workflow Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.workflow_name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.workflow_version',
    displayName: 'Files Sequencing Experiment Workflow Version',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::files.sequencing_experiment.workflow_version',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.study_id',
    displayName: 'Files Study Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::files.study_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'icd_tagged',
    displayName: 'Icd Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Participant::extended::icd_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'icd_tagged.age_at_event',
    displayName: 'Icd Tagged Age At Event',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::icd_tagged.age_at_event',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'icd_tagged.internal_phenotype_id',
    displayName: 'Icd Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::icd_tagged.internal_phenotype_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'icd_tagged.is_leaf',
    displayName: 'Icd Tagged Is Leaf',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::icd_tagged.is_leaf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'icd_tagged.is_tagged',
    displayName: 'Icd Tagged Is Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::icd_tagged.is_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'icd_tagged.name',
    displayName: 'Icd Tagged Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::icd_tagged.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'icd_tagged.parents',
    displayName: 'Icd Tagged Parents',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::icd_tagged.parents',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'icd_tagged.source_text',
    displayName: 'Icd Tagged Source Text',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::icd_tagged.source_text',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'is_a_proband',
    displayName: 'Is A Proband',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::is_a_proband',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'is_affected',
    displayName: 'Is Affected',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::is_affected',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo',
    displayName: 'Mondo',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Participant::extended::mondo',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo.age_at_event',
    displayName: 'Mondo Age At Event',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::mondo.age_at_event',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo.is_leaf',
    displayName: 'Mondo Is Leaf',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::mondo.is_leaf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo.is_tagged',
    displayName: 'Mondo Is Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::mondo.is_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo.name',
    displayName: 'Mondo Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::mondo.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo.parents',
    displayName: 'Mondo Parents',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::mondo.parents',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo_tagged',
    displayName: 'Mondo Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Participant::extended::mondo_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo_tagged.age_at_event',
    displayName: 'Mondo Tagged Age At Event',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::mondo_tagged.age_at_event',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo_tagged.internal_phenotype_id',
    displayName: 'Mondo Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::mondo_tagged.internal_phenotype_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo_tagged.is_leaf',
    displayName: 'Mondo Tagged Is Leaf',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::mondo_tagged.is_leaf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo_tagged.is_tagged',
    displayName: 'Mondo Tagged Is Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::mondo_tagged.is_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo_tagged.name',
    displayName: 'Mondo Tagged Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::mondo_tagged.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo_tagged.parents',
    displayName: 'Mondo Tagged Parents',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::mondo_tagged.parents',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo_tagged.source_text',
    displayName: 'Mondo Tagged Source Text',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::mondo_tagged.source_text',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'observed_phenotype_tagged',
    displayName: 'Observed Phenotype Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'observed_phenotype_tagged.age_at_event',
    displayName: 'Observed Phenotype Tagged Age At Event',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged.age_at_event',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'observed_phenotype_tagged.internal_phenotype_id',
    displayName: 'Observed Phenotype Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged.internal_phenotype_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'observed_phenotype_tagged.is_leaf',
    displayName: 'Observed Phenotype Tagged Is Leaf',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged.is_leaf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'observed_phenotype_tagged.is_tagged',
    displayName: 'Observed Phenotype Tagged Is Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged.is_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'observed_phenotype_tagged.name',
    displayName: 'Observed Phenotype Tagged Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'observed_phenotype_tagged.parents',
    displayName: 'Observed Phenotype Tagged Parents',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged.parents',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'observed_phenotype_tagged.source_text',
    displayName: 'Observed Phenotype Tagged Source Text',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::observed_phenotype_tagged.source_text',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'observed_phenotypes',
    displayName: 'Observed Phenotypes',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Participant::extended::observed_phenotypes',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'observed_phenotypes.age_at_event',
    displayName: 'Observed Phenotypes Age At Event',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::observed_phenotypes.age_at_event',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'observed_phenotypes.is_leaf',
    displayName: 'Observed Phenotypes Is Leaf',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::observed_phenotypes.is_leaf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'observed_phenotypes.is_tagged',
    displayName: 'Observed Phenotypes Is Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::observed_phenotypes.is_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'observed_phenotypes.name',
    displayName: 'Observed Phenotypes Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::observed_phenotypes.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'observed_phenotypes.parents',
    displayName: 'Observed Phenotypes Parents',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::observed_phenotypes.parents',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant_2_id',
    displayName: 'Participant 2 Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::participant_2_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant_id',
    displayName: 'Participant Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::participant_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'phenotypes_tagged',
    displayName: 'Phenotypes Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'phenotypes_tagged.age_at_event',
    displayName: 'Phenotypes Tagged Age At Event',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.age_at_event',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'phenotypes_tagged.internal_phenotype_id',
    displayName: 'Phenotypes Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.internal_phenotype_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'phenotypes_tagged.is_leaf',
    displayName: 'Phenotypes Tagged Is Leaf',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.is_leaf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'phenotypes_tagged.is_observed',
    displayName: 'Phenotypes Tagged Is Observed',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.is_observed',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'phenotypes_tagged.is_tagged',
    displayName: 'Phenotypes Tagged Is Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.is_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'phenotypes_tagged.name',
    displayName: 'Phenotypes Tagged Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'phenotypes_tagged.parents',
    displayName: 'Phenotypes Tagged Parents',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.parents',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'phenotypes_tagged.source_text',
    displayName: 'Phenotypes Tagged Source Text',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::phenotypes_tagged.source_text',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'relationship_to_proband',
    displayName: 'Relationship To Proband',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::relationship_to_proband',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'release_id',
    displayName: 'Release Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::release_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'security',
    displayName: 'Security',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::security',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'sex',
    displayName: 'Sex',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::sex',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study',
    displayName: 'Study',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Participant::extended::study',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.contact',
    displayName: 'Study Contact',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Participant::extended::study.contact',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.contact.type',
    displayName: 'Study Contact Type',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::study.contact.type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.contact.value',
    displayName: 'Study Contact Value',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::study.contact.value',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.data_access_codes',
    displayName: 'Study Data Access Codes',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Participant::extended::study.data_access_codes',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.data_access_codes.access_limitations',
    displayName: 'Study Data Access Codes Access Limitations',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::study.data_access_codes.access_limitations',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.data_access_codes.access_requirements',
    displayName: 'Study Data Access Codes Access Requirements',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::study.data_access_codes.access_requirements',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.domain',
    displayName: 'Study Domain',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::study.domain',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.name',
    displayName: 'Study Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::study.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.population',
    displayName: 'Study Population',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::study.population',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.study_code',
    displayName: 'Study Study Code',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::study.study_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_code',
    displayName: 'Study Code',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::study_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_id',
    displayName: 'Study Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::study_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'submitter_participant_id',
    displayName: 'Submitter Participant Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Participant::extended::submitter_participant_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'vital_status',
    displayName: 'Vital Status',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Participant::extended::vital_status',
    primaryKey: false,
  },
];

export default extendedMapping;
