const programs = {
  total: 4,
  edges: [
    {
      program_id: 'RARE-QC',
      name_en: 'RARE.Qc – The Network to Advance Rare Disease Research in Quebec',
      name_fr: 'RARE.Qc – Le réseau pour avancer la recherche en maladies rares au Québec',
      description_en:
        // eslint-disable-next-line max-len
        'RARE.Qc is a Quebec-based network focused on advancing research and innovation in the field of rare diseases. Its primary goal is to foster collaboration between researchers, healthcare professionals, institutions and government agencies to accelerate the development of treatments and improve understanding of rare conditions. The network provides a platform for sharing knowledge, data, and resources, facilitating interdisciplinary partnerships to address the unique challenges posed by rare diseases. The network is committed to driving progress through collective expertise and aims to contribute to the development of more effective therapies and diagnostic tools for rare diseases in Quebec and beyond.',
      description_fr:
        // eslint-disable-next-line max-len
        "RARE.Qc est un réseau québécois axé sur l'avancement de la recherche et de l'innovation dans le domaine des maladies rares. Son objectif principal est de favoriser la collaboration entre les chercheurs, les professionnels de la santé, les institutions et les organismes gouvernementaux afin d'accélérer la mise au point de traitements et d'améliorer la compréhension des maladies rares. Le réseau fournit une plateforme pour le partage des connaissances, des données et des ressources, facilitant les partenariats interdisciplinaires pour relever les défis uniques posés par les maladies rares. Le réseau s'engage à faire avancer les choses grâce à l'expertise collective et vise à contribuer au développement de thérapies et d'outils de diagnostic plus efficaces pour les maladies rares au Québec et ailleurs.",
      website: 'http://rare.quebec',
      citation_statement:
        // eslint-disable-next-line max-len
        'The results analyzed and presented here are based in whole or in part upon on data generated by the RARE-QC program. These data were accessed through CQDG’s databases',
      contacts: [
        {
          name: 'RARE.Qc Administration',
          email: 'info@rare.quebec',
          institution: 'RARE.Qc is based at the RI-MUHC',
        },
      ],
      managers: [
        {
          name: 'Layla Omar Al-Shaikh',
          picture_url: '/members_pictures/laylaomaralshaikh.png',
          role_fr: 'gestionnaire',
          role_en: 'manager',
          institution: 'CHU Sainte-Justine',
        },
      ],
      partners: [
        {
          name: 'FRQS',
          logo_url: '/partners_logos/FRQS.svg',
          rank: '2',
        },
        {
          name: 'Genome Quebec',
          logo_url: '/partners_logos/genome_qc.svg',
          rank: '1',
        },
      ],
      study_codes: ['STUDY1'],
      logo_url: '',
    },
    {
      program_id: 'RARE-QC2',
      name_en: 'RARE.Qc 2 – The Network to Advance Rare Disease Research in Quebec',
      name_fr: 'RARE.Qc 2 – Le réseau pour avancer la recherche en maladies rares au Québec',
      description_en:
        // eslint-disable-next-line max-len
        'RARE.Qc is a Quebec-based network focused on advancing research and innovation in the field of rare diseases. Its primary goal is to foster collaboration between researchers, healthcare professionals, institutions and government agencies to accelerate the development of treatments and improve understanding of rare conditions. The network provides a platform for sharing knowledge, data, and resources, facilitating interdisciplinary partnerships to address the unique challenges posed by rare diseases. The network is committed to driving progress through collective expertise and aims to contribute to the development of more effective therapies and diagnostic tools for rare diseases in Quebec and beyond.',
      description_fr:
        // eslint-disable-next-line max-len
        "RARE.Qc est un réseau québécois axé sur l'avancement de la recherche et de l'innovation dans le domaine des maladies rares. Son objectif principal est de favoriser la collaboration entre les chercheurs, les professionnels de la santé, les institutions et les organismes gouvernementaux afin d'accélérer la mise au point de traitements et d'améliorer la compréhension des maladies rares. Le réseau fournit une plateforme pour le partage des connaissances, des données et des ressources, facilitant les partenariats interdisciplinaires pour relever les défis uniques posés par les maladies rares. Le réseau s'engage à faire avancer les choses grâce à l'expertise collective et vise à contribuer au développement de thérapies et d'outils de diagnostic plus efficaces pour les maladies rares au Québec et ailleurs.",
      website: 'http://rare.quebec',
      citation_statement:
        // eslint-disable-next-line max-len
        'The results analyzed and presented here are based in whole or in part upon on data generated by the RARE-QC program. These data were accessed through CQDG’s databases',
      contacts: [
        {
          name: 'RARE.Qc Administration',
          email: 'info@rare.quebec',
          institution: 'RARE.Qc is based at the RI-MUHC',
        },
      ],
      managers: [
        {
          name: 'Layla Omar Al-Shaikh',
          picture_url: '/members_pictures/laylaomaralshaikh.png',
          role_fr: 'gestionnaire',
          role_en: 'manager',
          institution: 'CHU Sainte-Justine',
        },
      ],
      partners: [
        {
          name: 'FRQS',
          logo_url: '/partners_logos/FRQS.svg',
          rank: '2',
        },
        {
          name: 'Genome Quebec',
          logo_url: '/partners_logos/genome_qc.svg',
          rank: '1',
        },
      ],
      study_codes: ['STUDY1', 'STUDY3', 'T-DEE'],
      logo_url: '/programs_logos/rare.svg',
    },
    {
      program_id: 'RARE-QC3',
      name_en: 'RARE.Qc 3 – The Network to Advance Rare Disease Research in Quebec',
      name_fr: 'RARE.Qc 3 – Le réseau pour avancer la recherche en maladies rares au Québec',
      description_en:
        // eslint-disable-next-line max-len
        'RARE.Qc is a Quebec-based network focused on advancing research and innovation in the field of rare diseases. Its primary goal is to foster collaboration between researchers, healthcare professionals, institutions and government agencies to accelerate the development of treatments and improve understanding of rare conditions. The network provides a platform for sharing knowledge, data, and resources, facilitating interdisciplinary partnerships to address the unique challenges posed by rare diseases. The network is committed to driving progress through collective expertise and aims to contribute to the development of more effective therapies and diagnostic tools for rare diseases in Quebec and beyond.',
      description_fr:
        // eslint-disable-next-line max-len
        "RARE.Qc est un réseau québécois axé sur l'avancement de la recherche et de l'innovation dans le domaine des maladies rares. Son objectif principal est de favoriser la collaboration entre les chercheurs, les professionnels de la santé, les institutions et les organismes gouvernementaux afin d'accélérer la mise au point de traitements et d'améliorer la compréhension des maladies rares. Le réseau fournit une plateforme pour le partage des connaissances, des données et des ressources, facilitant les partenariats interdisciplinaires pour relever les défis uniques posés par les maladies rares. Le réseau s'engage à faire avancer les choses grâce à l'expertise collective et vise à contribuer au développement de thérapies et d'outils de diagnostic plus efficaces pour les maladies rares au Québec et ailleurs.",
      website: 'http://rare.quebec',
      citation_statement:
        // eslint-disable-next-line max-len
        'The results analyzed and presented here are based in whole or in part upon on data generated by the RARE-QC program. These data were accessed through CQDG’s databases',
      contacts: [
        {
          name: 'RARE.Qc Administration',
          email: 'info@rare.quebec',
          institution: 'RARE.Qc is based at the RI-MUHC',
        },
      ],
      managers: [
        {
          name: 'Layla Omar Al-Shaikh',
          picture_url: '/members_pictures/laylaomaralshaikh.png',
          role_fr: 'gestionnaire',
          role_en: 'manager',
          institution: 'CHU Sainte-Justine',
        },
        {
          name: 'Esther Howard',
          picture_url: '/members_pictures/estherhoward.png',
          role_fr: 'gestionnaire',
          role_en: 'manager',
          institution: 'CHU Sainte-Justine',
        },
        {
          name: 'James Bennett',
          picture_url: '/members_pictures/jamesbennett.png',
          role_fr: 'gestionnaire',
          role_en: 'manager',
          institution: 'CHU Sainte-Justine',
        },
        {
          name: 'Ralph Edwards',
          picture_url: '/members_pictures/ralphedwards.png',
          role_fr: 'gestionnaire',
          role_en: 'manager',
          institution: 'CHU Sainte-Justine',
        },
      ],
      partners: [
        {
          name: 'FRQS',
          logo_url: '/partners_logos/FRQS.svg',
          rank: '2',
        },
        {
          name: 'Genome Quebec',
          logo_url: '/partners_logos/genome_qc.svg',
          rank: '1',
        },
        {
          name: 'CHU Sainte-Justine',
          logo_url: '/partners_logos/CHUSJ.svg',
          rank: '3',
        },
        {
          name: 'CQDG',
          logo_url: '/partners_logos/CQDG.svg',
          rank: '4',
        },
        {
          name: 'FCI',
          logo_url: '/partners_logos/FCI.svg',
          rank: '5',
        },
        {
          name: 'INESSS',
          logo_url: '/partners_logos/INESSS.svg',
          rank: '7',
        },
        {
          name: 'MSSSQ',
          logo_url: '/partners_logos/MSSSQ.svg',
          rank: '8',
        },
        {
          name: 'RQDM',
          logo_url: '/partners_logos/RQDM.svg',
          rank: '9',
        },
        {
          name: 'Axelys',
          logo_url: '/partners_logos/axelys.svg',
          rank: '10',
        },
        {
          name: 'Ferlab',
          logo_url: '/partners_logos/ferlab.svg',
          rank: '11',
        },
        {
          name: 'Invivo',
          logo_url: '/partners_logos/invivo.svg',
          rank: '13',
        },
        {
          name: 'SD4H',
          logo_url: '/partners_logos/sd4h.png',
          rank: '14',
        },
      ],
      study_codes: ['STUDY1', 'STUDY2', 'STUDY3', 'T-DEE'],
      logo_url: '/programs_logos/rare.svg',
    },
    {
      program_id: 'RARE-QC4',
      name_en: 'RARE.Qc 4 – The Network to Advance Rare Disease Research in Quebec',
      name_fr: 'RARE.Qc 4 – Le réseau pour avancer la recherche en maladies rares au Québec',
      description_en:
        // eslint-disable-next-line max-len
        'RARE.Qc is a Quebec-based network focused on advancing research and innovation in the field of rare diseases. Its primary goal is to foster collaboration between researchers, healthcare professionals, institutions and government agencies to accelerate the development of treatments and improve understanding of rare conditions. The network provides a platform for sharing knowledge, data, and resources, facilitating interdisciplinary partnerships to address the unique challenges posed by rare diseases. The network is committed to driving progress through collective expertise and aims to contribute to the development of more effective therapies and diagnostic tools for rare diseases in Quebec and beyond.',
      description_fr:
        // eslint-disable-next-line max-len
        "RARE.Qc est un réseau québécois axé sur l'avancement de la recherche et de l'innovation dans le domaine des maladies rares. Son objectif principal est de favoriser la collaboration entre les chercheurs, les professionnels de la santé, les institutions et les organismes gouvernementaux afin d'accélérer la mise au point de traitements et d'améliorer la compréhension des maladies rares. Le réseau fournit une plateforme pour le partage des connaissances, des données et des ressources, facilitant les partenariats interdisciplinaires pour relever les défis uniques posés par les maladies rares. Le réseau s'engage à faire avancer les choses grâce à l'expertise collective et vise à contribuer au développement de thérapies et d'outils de diagnostic plus efficaces pour les maladies rares au Québec et ailleurs.",
      website: 'http://rare.quebec',
      citation_statement:
        // eslint-disable-next-line max-len
        'The results analyzed and presented here are based in whole or in part upon on data generated by the RARE-QC program. These data were accessed through CQDG’s databases',
      contacts: [
        {
          name: 'RARE.Qc Administration',
          email: 'info@rare.quebec',
          institution: 'RARE.Qc is based at the RI-MUHC',
        },
      ],
      managers: [
        {
          name: 'Layla Omar Al-Shaikh',
          picture_url: '/members_pictures/laylaomaralshaikh.png',
          role_fr: 'gestionnaire',
          role_en: 'manager',
          institution: 'CHU Sainte-Justine',
        },
      ],
      partners: [
        {
          name: 'FRQS',
          logo_url: '/partners_logos/FRQS.svg',
          rank: '2',
        },
        {
          name: 'Genome Quebec',
          logo_url: '/partners_logos/genome_qc.svg',
          rank: '1',
        },
      ],
      study_codes: ['STUDY1', 'STUDY3'],
      logo_url: '',
    },
  ],
};

export default programs;
