const extendedMapping = [
  {
    field: 'age_biospecimen_collection',
    type: 'keyword',
    displayName: 'Age Biospecimen Collection',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::age_biospecimen_collection',
  },
  {
    field: 'biospecimen_id',
    type: 'id',
    displayName: 'Biospecimen Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::biospecimen_id',
  },
  {
    field: 'biospecimen_tissue_source',
    type: 'keyword',
    displayName: 'Biospecimen Tissue Source',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::biospecimen_tissue_source',
  },
  {
    field: 'files',
    type: 'nested',
    displayName: 'Files',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files',
  },
  {
    field: 'files.biospecimen_reference',
    type: 'keyword',
    displayName: 'Files Biospecimen Reference',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.biospecimen_reference',
  },
  {
    field: 'files.data_category',
    type: 'keyword',
    displayName: 'Files Data Category',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.data_category',
  },
  {
    field: 'files.data_type',
    type: 'keyword',
    displayName: 'Files Data Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.data_type',
  },
  {
    field: 'files.dataset',
    type: 'keyword',
    displayName: 'Files Dataset',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.dataset',
  },
  {
    field: 'files.ferload_url',
    type: 'keyword',
    displayName: 'Files Ferload Url',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.ferload_url',
  },
  {
    field: 'files.file_2_id',
    type: 'id',
    displayName: 'Files File 2 Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.file_2_id',
  },
  {
    field: 'files.file_format',
    type: 'keyword',
    displayName: 'Files File Format',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.file_format',
  },
  {
    field: 'files.file_hash',
    type: 'keyword',
    displayName: 'Files File Hash',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.file_hash',
  },
  {
    field: 'files.file_id',
    type: 'id',
    displayName: 'Files File Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.file_id',
  },
  {
    field: 'files.file_name',
    type: 'keyword',
    displayName: 'Files File Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.file_name',
  },
  {
    field: 'files.file_size',
    type: 'float',
    displayName: 'Files File Size',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 0.01,
    gqlId: 'cqdg::Biospecimen::extended::files.file_size',
  },
  {
    field: 'files.relates_to',
    type: 'keyword',
    displayName: 'Files Relates To',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.relates_to',
  },
  {
    field: 'files.sample',
    type: 'object',
    displayName: 'Files Sample',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sample',
  },
  {
    field: 'files.sample.lab_aliquot_ids',
    type: 'id',
    displayName: 'Files Sample Lab Aliquot Ids',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sample.lab_aliquot_ids',
  },
  {
    field: 'files.sample.ldm_sample_id',
    type: 'id',
    displayName: 'Files Sample Ldm Sample Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sample.ldm_sample_id',
  },
  {
    field: 'files.sequencing_experiment',
    type: 'object',
    displayName: 'Files Sequencing Experiment',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment',
  },
  {
    field: 'files.sequencing_experiment.analysis_files',
    type: 'object',
    displayName: 'Files Sequencing Experiment Analysis Files',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.analysis_files',
  },
  {
    field: 'files.sequencing_experiment.analysis_files.data_type',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Analysis Files Data Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.analysis_files.data_type',
  },
  {
    field: 'files.sequencing_experiment.analysis_files.file_id',
    type: 'id',
    displayName: 'Files Sequencing Experiment Analysis Files File Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.analysis_files.file_id',
  },
  {
    field: 'files.sequencing_experiment.analysis_id',
    type: 'id',
    displayName: 'Files Sequencing Experiment Analysis Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.analysis_id',
  },
  {
    field: 'files.sequencing_experiment.bio_informatic_analysis',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Bio Informatic Analysis',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.bio_informatic_analysis',
  },
  {
    field: 'files.sequencing_experiment.capture_kit',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Capture Kit',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.capture_kit',
  },
  {
    field: 'files.sequencing_experiment.experimental_strategy',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Experimental Strategy',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.experimental_strategy',
  },
  {
    field: 'files.sequencing_experiment.experimental_strategy_1',
    type: 'object',
    displayName: 'Files Sequencing Experiment Experimental Strategy 1',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.experimental_strategy_1',
  },
  {
    field: 'files.sequencing_experiment.experimental_strategy_1.code',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Experimental Strategy 1 Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.experimental_strategy_1.code',
  },
  {
    field: 'files.sequencing_experiment.experimental_strategy_1.display',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Experimental Strategy 1 Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.experimental_strategy_1.display',
  },
  {
    field: 'files.sequencing_experiment.genome_build',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Genome Build',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.genome_build',
  },
  {
    field: 'files.sequencing_experiment.labAliquotID',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Lab Aliquot ID',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.labAliquotID',
  },
  {
    field: 'files.sequencing_experiment.owner',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Owner',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.owner',
  },
  {
    field: 'files.sequencing_experiment.pipeline',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Pipeline',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.pipeline',
  },
  {
    field: 'files.sequencing_experiment.platform',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Platform',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.platform',
  },
  {
    field: 'files.sequencing_experiment.protocol',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Protocol',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.protocol',
  },
  {
    field: 'files.sequencing_experiment.read_length',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Read Length',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.read_length',
  },
  {
    field: 'files.sequencing_experiment.run_alias',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Run Alias',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.run_alias',
  },
  {
    field: 'files.sequencing_experiment.run_date',
    type: 'date',
    displayName: 'Files Sequencing Experiment Run Date',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.run_date',
  },
  {
    field: 'files.sequencing_experiment.run_dates',
    type: 'date',
    displayName: 'Files Sequencing Experiment Run Dates',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.run_dates',
  },
  {
    field: 'files.sequencing_experiment.run_ids',
    type: 'id',
    displayName: 'Files Sequencing Experiment Run Ids',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.run_ids',
  },
  {
    field: 'files.sequencing_experiment.run_name',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Run Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.run_name',
  },
  {
    field: 'files.sequencing_experiment.selection',
    type: 'object',
    displayName: 'Files Sequencing Experiment Selection',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.selection',
  },
  {
    field: 'files.sequencing_experiment.selection.code',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Selection Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.selection.code',
  },
  {
    field: 'files.sequencing_experiment.selection.display',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Selection Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.selection.display',
  },
  {
    field: 'files.sequencing_experiment.sequencer_id',
    type: 'id',
    displayName: 'Files Sequencing Experiment Sequencer Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.sequencer_id',
  },
  {
    field: 'files.sequencing_experiment.source',
    type: 'object',
    displayName: 'Files Sequencing Experiment Source',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.source',
  },
  {
    field: 'files.sequencing_experiment.source.code',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Source Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.source.code',
  },
  {
    field: 'files.sequencing_experiment.source.display',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Source Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.source.display',
  },
  {
    field: 'files.sequencing_experiment.target_capture_kit',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Target Capture Kit',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.target_capture_kit',
  },
  {
    field: 'files.sequencing_experiment.target_loci',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Target Loci',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.target_loci',
  },
  {
    field: 'files.sequencing_experiment.type_of_sequencing',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Type Of Sequencing',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.type_of_sequencing',
  },
  {
    field: 'files.sequencing_experiment.workflow_name',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Workflow Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.workflow_name',
  },
  {
    field: 'files.sequencing_experiment.workflow_version',
    type: 'keyword',
    displayName: 'Files Sequencing Experiment Workflow Version',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.workflow_version',
  },
  {
    field: 'participant',
    type: 'object',
    displayName: 'Participant',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant',
  },
  {
    field: 'participant.age_at_recruitment',
    type: 'keyword',
    displayName: 'Participant Age At Recruitment',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.age_at_recruitment',
  },
  {
    field: 'participant.age_of_death',
    type: 'keyword',
    displayName: 'Participant Age Of Death',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.age_of_death',
  },
  {
    field: 'participant.cause_of_death',
    type: 'keyword',
    displayName: 'Participant Cause Of Death',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.cause_of_death',
  },
  {
    field: 'participant.diagnoses',
    type: 'nested',
    displayName: 'Participant Diagnoses',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses',
  },
  {
    field: 'participant.diagnoses.age_at_diagnosis',
    type: 'keyword',
    displayName: 'Participant Diagnoses Age At Diagnosis',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses.age_at_diagnosis',
  },
  {
    field: 'participant.diagnoses.diagnosis_ICD_code',
    type: 'keyword',
    displayName: 'Participant Diagnoses Diagnosis ICD Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses.diagnosis_ICD_code',
  },
  {
    field: 'participant.diagnoses.diagnosis_icd_display',
    type: 'keyword',
    displayName: 'Participant Diagnoses Diagnosis Icd Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses.diagnosis_icd_display',
  },
  {
    field: 'participant.diagnoses.diagnosis_mondo_code',
    type: 'keyword',
    displayName: 'Participant Diagnoses Diagnosis Mondo Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses.diagnosis_mondo_code',
  },
  {
    field: 'participant.diagnoses.diagnosis_mondo_display',
    type: 'keyword',
    displayName: 'Participant Diagnoses Diagnosis Mondo Display',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses.diagnosis_mondo_display',
  },
  {
    field: 'participant.diagnoses.diagnosis_source_text',
    type: 'keyword',
    displayName: 'Participant Diagnoses Diagnosis Source Text',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses.diagnosis_source_text',
  },
  {
    field: 'participant.diagnoses.fhir_id',
    type: 'id',
    displayName: 'Participant Diagnoses Fhir Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses.fhir_id',
  },
  {
    field: 'participant.ethnicity',
    type: 'keyword',
    displayName: 'Participant Ethnicity',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.ethnicity',
  },
  {
    field: 'participant.family_id',
    type: 'id',
    displayName: 'Participant Family Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.family_id',
  },
  {
    field: 'participant.family_relationships',
    type: 'nested',
    displayName: 'Participant Family Relationships',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships',
  },
  {
    field: 'participant.family_relationships.family_id',
    type: 'id',
    displayName: 'Participant Family Relationships Family Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.family_id',
  },
  {
    field: 'participant.family_relationships.family_type',
    type: 'keyword',
    displayName: 'Participant Family Relationships Family Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.family_type',
  },
  {
    field: 'participant.family_relationships.focus_participant_id',
    type: 'id',
    displayName: 'Participant Family Relationships Focus Participant Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.focus_participant_id',
  },
  {
    field: 'participant.family_relationships.is_affected',
    type: 'keyword',
    displayName: 'Participant Family Relationships Is Affected',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.is_affected',
  },
  {
    field: 'participant.family_relationships.participant_id',
    type: 'id',
    displayName: 'Participant Family Relationships Participant Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.participant_id',
  },
  {
    field: 'participant.family_relationships.relationship_to_proband',
    type: 'keyword',
    displayName: 'Participant Family Relationships Relationship To Proband',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.relationship_to_proband',
  },
  {
    field: 'participant.family_relationships.submitter_family_id',
    type: 'id',
    displayName: 'Participant Family Relationships Submitter Family Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.submitter_family_id',
  },
  {
    field: 'participant.family_relationships.submitter_participant_id',
    type: 'id',
    displayName: 'Participant Family Relationships Submitter Participant Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.submitter_participant_id',
  },
  {
    field: 'participant.family_type',
    type: 'keyword',
    displayName: 'Participant Family Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.family_type',
  },
  {
    field: 'participant.icd_tagged',
    type: 'nested',
    displayName: 'Participant Icd Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged',
  },
  {
    field: 'participant.icd_tagged.age_at_event',
    type: 'keyword',
    displayName: 'Participant Icd Tagged Age At Event',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged.age_at_event',
  },
  {
    field: 'participant.icd_tagged.internal_phenotype_id',
    type: 'id',
    displayName: 'Participant Icd Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged.internal_phenotype_id',
  },
  {
    field: 'participant.icd_tagged.is_leaf',
    type: 'boolean',
    displayName: 'Participant Icd Tagged Is Leaf',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged.is_leaf',
  },
  {
    field: 'participant.icd_tagged.is_tagged',
    type: 'boolean',
    displayName: 'Participant Icd Tagged Is Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged.is_tagged',
  },
  {
    field: 'participant.icd_tagged.name',
    type: 'keyword',
    displayName: 'Participant Icd Tagged Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged.name',
  },
  {
    field: 'participant.icd_tagged.parents',
    type: 'keyword',
    displayName: 'Participant Icd Tagged Parents',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged.parents',
  },
  {
    field: 'participant.icd_tagged.source_text',
    type: 'keyword',
    displayName: 'Participant Icd Tagged Source Text',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged.source_text',
  },
  {
    field: 'participant.is_a_proband',
    type: 'boolean',
    displayName: 'Participant Is A Proband',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.is_a_proband',
  },
  {
    field: 'participant.is_affected',
    type: 'keyword',
    displayName: 'Participant Is Affected',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.is_affected',
  },
  {
    field: 'participant.mondo',
    type: 'nested',
    displayName: 'Participant Mondo',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo',
  },
  {
    field: 'participant.mondo.age_at_event',
    type: 'keyword',
    displayName: 'Participant Mondo Age At Event',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo.age_at_event',
  },
  {
    field: 'participant.mondo.is_leaf',
    type: 'boolean',
    displayName: 'Participant Mondo Is Leaf',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo.is_leaf',
  },
  {
    field: 'participant.mondo.is_tagged',
    type: 'boolean',
    displayName: 'Participant Mondo Is Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo.is_tagged',
  },
  {
    field: 'participant.mondo.name',
    type: 'keyword',
    displayName: 'Participant Mondo Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo.name',
  },
  {
    field: 'participant.mondo.parents',
    type: 'keyword',
    displayName: 'Participant Mondo Parents',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo.parents',
  },
  {
    field: 'participant.mondo_tagged',
    type: 'nested',
    displayName: 'Participant Mondo Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged',
  },
  {
    field: 'participant.mondo_tagged.age_at_event',
    type: 'keyword',
    displayName: 'Participant Mondo Tagged Age At Event',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged.age_at_event',
  },
  {
    field: 'participant.mondo_tagged.internal_phenotype_id',
    type: 'id',
    displayName: 'Participant Mondo Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged.internal_phenotype_id',
  },
  {
    field: 'participant.mondo_tagged.is_leaf',
    type: 'boolean',
    displayName: 'Participant Mondo Tagged Is Leaf',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged.is_leaf',
  },
  {
    field: 'participant.mondo_tagged.is_tagged',
    type: 'boolean',
    displayName: 'Participant Mondo Tagged Is Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged.is_tagged',
  },
  {
    field: 'participant.mondo_tagged.name',
    type: 'keyword',
    displayName: 'Participant Mondo Tagged Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged.name',
  },
  {
    field: 'participant.mondo_tagged.parents',
    type: 'keyword',
    displayName: 'Participant Mondo Tagged Parents',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged.parents',
  },
  {
    field: 'participant.mondo_tagged.source_text',
    type: 'keyword',
    displayName: 'Participant Mondo Tagged Source Text',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged.source_text',
  },
  {
    field: 'participant.observed_phenotype_tagged',
    type: 'nested',
    displayName: 'Participant Observed Phenotype Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged',
  },
  {
    field: 'participant.observed_phenotype_tagged.age_at_event',
    type: 'keyword',
    displayName: 'Participant Observed Phenotype Tagged Age At Event',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged.age_at_event',
  },
  {
    field: 'participant.observed_phenotype_tagged.internal_phenotype_id',
    type: 'id',
    displayName: 'Participant Observed Phenotype Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged.internal_phenotype_id',
  },
  {
    field: 'participant.observed_phenotype_tagged.is_leaf',
    type: 'boolean',
    displayName: 'Participant Observed Phenotype Tagged Is Leaf',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged.is_leaf',
  },
  {
    field: 'participant.observed_phenotype_tagged.is_tagged',
    type: 'boolean',
    displayName: 'Participant Observed Phenotype Tagged Is Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged.is_tagged',
  },
  {
    field: 'participant.observed_phenotype_tagged.name',
    type: 'keyword',
    displayName: 'Participant Observed Phenotype Tagged Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged.name',
  },
  {
    field: 'participant.observed_phenotype_tagged.parents',
    type: 'keyword',
    displayName: 'Participant Observed Phenotype Tagged Parents',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged.parents',
  },
  {
    field: 'participant.observed_phenotype_tagged.source_text',
    type: 'keyword',
    displayName: 'Participant Observed Phenotype Tagged Source Text',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged.source_text',
  },
  {
    field: 'participant.observed_phenotypes',
    type: 'nested',
    displayName: 'Participant Observed Phenotypes',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotypes',
  },
  {
    field: 'participant.observed_phenotypes.age_at_event',
    type: 'keyword',
    displayName: 'Participant Observed Phenotypes Age At Event',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotypes.age_at_event',
  },
  {
    field: 'participant.observed_phenotypes.is_leaf',
    type: 'boolean',
    displayName: 'Participant Observed Phenotypes Is Leaf',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotypes.is_leaf',
  },
  {
    field: 'participant.observed_phenotypes.is_tagged',
    type: 'boolean',
    displayName: 'Participant Observed Phenotypes Is Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotypes.is_tagged',
  },
  {
    field: 'participant.observed_phenotypes.name',
    type: 'keyword',
    displayName: 'Participant Observed Phenotypes Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotypes.name',
  },
  {
    field: 'participant.observed_phenotypes.parents',
    type: 'keyword',
    displayName: 'Participant Observed Phenotypes Parents',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotypes.parents',
  },
  {
    field: 'participant.participant_2_id',
    type: 'id',
    displayName: 'Participant Participant 2 Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.participant_2_id',
  },
  {
    field: 'participant.participant_id',
    type: 'id',
    displayName: 'Participant Participant Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.participant_id',
  },
  {
    field: 'participant.phenotypes_tagged',
    type: 'nested',
    displayName: 'Participant Phenotypes Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged',
  },
  {
    field: 'participant.phenotypes_tagged.age_at_event',
    type: 'keyword',
    displayName: 'Participant Phenotypes Tagged Age At Event',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.age_at_event',
  },
  {
    field: 'participant.phenotypes_tagged.internal_phenotype_id',
    type: 'id',
    displayName: 'Participant Phenotypes Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.internal_phenotype_id',
  },
  {
    field: 'participant.phenotypes_tagged.is_leaf',
    type: 'boolean',
    displayName: 'Participant Phenotypes Tagged Is Leaf',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.is_leaf',
  },
  {
    field: 'participant.phenotypes_tagged.is_observed',
    type: 'boolean',
    displayName: 'Participant Phenotypes Tagged Is Observed',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.is_observed',
  },
  {
    field: 'participant.phenotypes_tagged.is_tagged',
    type: 'boolean',
    displayName: 'Participant Phenotypes Tagged Is Tagged',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.is_tagged',
  },
  {
    field: 'participant.phenotypes_tagged.name',
    type: 'keyword',
    displayName: 'Participant Phenotypes Tagged Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.name',
  },
  {
    field: 'participant.phenotypes_tagged.parents',
    type: 'keyword',
    displayName: 'Participant Phenotypes Tagged Parents',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.parents',
  },
  {
    field: 'participant.phenotypes_tagged.source_text',
    type: 'keyword',
    displayName: 'Participant Phenotypes Tagged Source Text',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.source_text',
  },
  {
    field: 'participant.relationship_to_proband',
    type: 'keyword',
    displayName: 'Participant Relationship To Proband',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.relationship_to_proband',
  },
  {
    field: 'participant.sex',
    type: 'keyword',
    displayName: 'Participant Sex',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.sex',
  },
  {
    field: 'participant.study',
    type: 'object',
    displayName: 'Participant Study',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.study',
  },
  {
    field: 'participant.study.study_code',
    type: 'keyword',
    displayName: 'Participant Study Study Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.study.study_code',
  },
  {
    field: 'participant.study_code',
    type: 'keyword',
    displayName: 'Participant Study Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.study_code',
  },
  {
    field: 'participant.study_id',
    type: 'id',
    displayName: 'Participant Study Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.study_id',
  },
  {
    field: 'participant.submitter_participant_id',
    type: 'id',
    displayName: 'Participant Submitter Participant Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.submitter_participant_id',
  },
  {
    field: 'participant.vital_status',
    type: 'keyword',
    displayName: 'Participant Vital Status',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::participant.vital_status',
  },
  {
    field: 'sample_2_id',
    type: 'id',
    displayName: 'Sample 2 Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::sample_2_id',
  },
  {
    field: 'sample_id',
    type: 'id',
    displayName: 'Sample Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::sample_id',
  },
  {
    field: 'sample_type',
    type: 'keyword',
    displayName: 'Sample Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::sample_type',
  },
  {
    field: 'security',
    type: 'keyword',
    displayName: 'Security',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::security',
  },
  {
    field: 'study',
    type: 'object',
    displayName: 'Study',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study',
  },
  {
    field: 'study.access_authority',
    type: 'object',
    displayName: 'Study Access Authority',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study.access_authority',
  },
  {
    field: 'study.access_authority.type',
    type: 'keyword',
    displayName: 'Study Access Authority Type',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study.access_authority.type',
  },
  {
    field: 'study.access_authority.value',
    type: 'keyword',
    displayName: 'Study Access Authority Value',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study.access_authority.value',
  },
  {
    field: 'study.data_access_codes',
    type: 'object',
    displayName: 'Study Data Access Codes',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study.data_access_codes',
  },
  {
    field: 'study.data_access_codes.access_limitations',
    type: 'keyword',
    displayName: 'Study Data Access Codes Access Limitations',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study.data_access_codes.access_limitations',
  },
  {
    field: 'study.data_access_codes.access_requirements',
    type: 'keyword',
    displayName: 'Study Data Access Codes Access Requirements',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study.data_access_codes.access_requirements',
  },
  {
    field: 'study.domain',
    type: 'keyword',
    displayName: 'Study Domain',
    active: false,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study.domain',
  },
  {
    field: 'study.name',
    type: 'keyword',
    displayName: 'Study Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study.name',
  },
  {
    field: 'study.population',
    type: 'keyword',
    displayName: 'Study Population',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study.population',
  },
  {
    field: 'study.programs',
    type: 'nested',
    displayName: 'Study Programs',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study.programs',
  },
  {
    field: 'study.programs.name_en',
    type: 'keyword',
    displayName: 'Study Programs Name En',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study.programs.name_en',
  },
  {
    field: 'study.programs.name_fr',
    type: 'keyword',
    displayName: 'Study Programs Name Fr',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study.programs.name_fr',
  },
  {
    field: 'study.programs.program_id',
    type: 'id',
    displayName: 'Study Programs Program Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study.programs.program_id',
  },
  {
    field: 'study.study_code',
    type: 'keyword',
    displayName: 'Study Study Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study.study_code',
  },
  {
    field: 'study_code',
    type: 'keyword',
    displayName: 'Study Code',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study_code',
  },
  {
    field: 'study_id',
    type: 'id',
    displayName: 'Study Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::study_id',
  },
  {
    field: 'submitter_biospecimen_id',
    type: 'id',
    displayName: 'Submitter Biospecimen Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::submitter_biospecimen_id',
  },
  {
    field: 'submitter_sample_id',
    type: 'id',
    displayName: 'Submitter Sample Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
    gqlId: 'cqdg::Biospecimen::extended::submitter_sample_id',
  },
];

export default extendedMapping;
