const extendedMapping = [
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'age_biospecimen_collection',
    displayName: 'Age Biospecimen Collection',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::age_biospecimen_collection',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'biospecimen_id',
    displayName: 'Biospecimen Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::biospecimen_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'biospecimen_tissue_source',
    displayName: 'Biospecimen Tissue Source',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::biospecimen_tissue_source',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files',
    displayName: 'Files',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Biospecimen::extended::files',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.biospecimen_reference',
    displayName: 'Files Biospecimen Reference',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.biospecimen_reference',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.data_category',
    displayName: 'Files Data Category',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.data_category',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.data_type',
    displayName: 'Files Data Type',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.data_type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.dataset',
    displayName: 'Files Dataset',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.dataset',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.ferload_url',
    displayName: 'Files Ferload Url',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.ferload_url',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.file_2_id',
    displayName: 'Files File 2 Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::files.file_2_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.file_format',
    displayName: 'Files File Format',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.file_format',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.file_hash',
    displayName: 'Files File Hash',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.file_hash',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.file_id',
    displayName: 'Files File Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::files.file_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.file_name',
    displayName: 'Files File Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.file_name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.file_size',
    displayName: 'Files File Size',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Biospecimen::extended::files.file_size',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.relates_to',
    displayName: 'Files Relates To',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.relates_to',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment',
    displayName: 'Files Sequencing Experiment',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.alir',
    displayName: 'Files Sequencing Experiment Alir',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.alir',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.analysis_id',
    displayName: 'Files Sequencing Experiment Analysis Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.analysis_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.bio_informatic_analysis',
    displayName: 'Files Sequencing Experiment Bio Informatic Analysis',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.bio_informatic_analysis',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.capture_kit',
    displayName: 'Files Sequencing Experiment Capture Kit',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.capture_kit',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.experimental_strategy',
    displayName: 'Files Sequencing Experiment Experimental Strategy',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.experimental_strategy',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.gcnv',
    displayName: 'Files Sequencing Experiment Gcnv',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.gcnv',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.genome_build',
    displayName: 'Files Sequencing Experiment Genome Build',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.genome_build',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.gsv',
    displayName: 'Files Sequencing Experiment Gsv',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.gsv',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.labAliquotID',
    displayName: 'Files Sequencing Experiment Lab Aliquot ID',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.labAliquotID',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.ldm_sample_id',
    displayName: 'Files Sequencing Experiment Ldm Sample Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.ldm_sample_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.owner',
    displayName: 'Files Sequencing Experiment Owner',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.owner',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.platform',
    displayName: 'Files Sequencing Experiment Platform',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.platform',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.read_length',
    displayName: 'Files Sequencing Experiment Read Length',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.read_length',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.run_alias',
    displayName: 'Files Sequencing Experiment Run Alias',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.run_alias',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.run_date',
    displayName: 'Files Sequencing Experiment Run Date',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'date',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.run_date',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.run_name',
    displayName: 'Files Sequencing Experiment Run Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.run_name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.sequencer_id',
    displayName: 'Files Sequencing Experiment Sequencer Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.sequencer_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.snv',
    displayName: 'Files Sequencing Experiment Snv',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.snv',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.ssup',
    displayName: 'Files Sequencing Experiment Ssup',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.ssup',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.type_of_sequencing',
    displayName: 'Files Sequencing Experiment Type Of Sequencing',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.type_of_sequencing',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.workflow_name',
    displayName: 'Files Sequencing Experiment Workflow Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.workflow_name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'files.sequencing_experiment.workflow_version',
    displayName: 'Files Sequencing Experiment Workflow Version',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::files.sequencing_experiment.workflow_version',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant',
    displayName: 'Participant',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Biospecimen::extended::participant',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.age_at_recruitment',
    displayName: 'Participant Age At Recruitment',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.age_at_recruitment',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.age_of_death',
    displayName: 'Participant Age Of Death',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.age_of_death',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.cause_of_death',
    displayName: 'Participant Cause Of Death',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.cause_of_death',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.diagnoses',
    displayName: 'Participant Diagnoses',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.diagnoses.age_at_diagnosis',
    displayName: 'Participant Diagnoses Age At Diagnosis',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses.age_at_diagnosis',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.diagnoses.diagnosis_ICD_code',
    displayName: 'Participant Diagnoses Diagnosis ICD Code',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses.diagnosis_ICD_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.diagnoses.diagnosis_icd_display',
    displayName: 'Participant Diagnoses Diagnosis Icd Display',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses.diagnosis_icd_display',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.diagnoses.diagnosis_mondo_code',
    displayName: 'Participant Diagnoses Diagnosis Mondo Code',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses.diagnosis_mondo_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.diagnoses.diagnosis_mondo_display',
    displayName: 'Participant Diagnoses Diagnosis Mondo Display',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses.diagnosis_mondo_display',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.diagnoses.diagnosis_source_text',
    displayName: 'Participant Diagnoses Diagnosis Source Text',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses.diagnosis_source_text',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.diagnoses.fhir_id',
    displayName: 'Participant Diagnoses Fhir Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.diagnoses.fhir_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.ethnicity',
    displayName: 'Participant Ethnicity',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.ethnicity',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.family_id',
    displayName: 'Participant Family Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.family_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.family_relationships',
    displayName: 'Participant Family Relationships',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.family_relationships.family_id',
    displayName: 'Participant Family Relationships Family Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.family_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.family_relationships.family_type',
    displayName: 'Participant Family Relationships Family Type',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.family_type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.family_relationships.focus_participant_id',
    displayName: 'Participant Family Relationships Focus Participant Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.focus_participant_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.family_relationships.is_affected',
    displayName: 'Participant Family Relationships Is Affected',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.is_affected',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.family_relationships.participant_id',
    displayName: 'Participant Family Relationships Participant Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.participant_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.family_relationships.relationship_to_proband',
    displayName: 'Participant Family Relationships Relationship To Proband',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.relationship_to_proband',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.family_relationships.submitter_family_id',
    displayName: 'Participant Family Relationships Submitter Family Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.submitter_family_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.family_relationships.submitter_participant_id',
    displayName: 'Participant Family Relationships Submitter Participant Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.family_relationships.submitter_participant_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.family_type',
    displayName: 'Participant Family Type',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.family_type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.icd_tagged',
    displayName: 'Participant Icd Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.icd_tagged.age_at_event',
    displayName: 'Participant Icd Tagged Age At Event',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged.age_at_event',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.icd_tagged.internal_phenotype_id',
    displayName: 'Participant Icd Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged.internal_phenotype_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.icd_tagged.is_leaf',
    displayName: 'Participant Icd Tagged Is Leaf',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged.is_leaf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.icd_tagged.is_tagged',
    displayName: 'Participant Icd Tagged Is Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged.is_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.icd_tagged.name',
    displayName: 'Participant Icd Tagged Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.icd_tagged.parents',
    displayName: 'Participant Icd Tagged Parents',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged.parents',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.icd_tagged.source_text',
    displayName: 'Participant Icd Tagged Source Text',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.icd_tagged.source_text',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.is_a_proband',
    displayName: 'Participant Is A Proband',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Biospecimen::extended::participant.is_a_proband',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.is_affected',
    displayName: 'Participant Is Affected',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.is_affected',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.mondo',
    displayName: 'Participant Mondo',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.mondo.age_at_event',
    displayName: 'Participant Mondo Age At Event',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo.age_at_event',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.mondo.is_leaf',
    displayName: 'Participant Mondo Is Leaf',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo.is_leaf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.mondo.is_tagged',
    displayName: 'Participant Mondo Is Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo.is_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.mondo.name',
    displayName: 'Participant Mondo Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.mondo.parents',
    displayName: 'Participant Mondo Parents',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo.parents',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.mondo_tagged',
    displayName: 'Participant Mondo Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.mondo_tagged.age_at_event',
    displayName: 'Participant Mondo Tagged Age At Event',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged.age_at_event',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.mondo_tagged.internal_phenotype_id',
    displayName: 'Participant Mondo Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged.internal_phenotype_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.mondo_tagged.is_leaf',
    displayName: 'Participant Mondo Tagged Is Leaf',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged.is_leaf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.mondo_tagged.is_tagged',
    displayName: 'Participant Mondo Tagged Is Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged.is_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.mondo_tagged.name',
    displayName: 'Participant Mondo Tagged Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.mondo_tagged.parents',
    displayName: 'Participant Mondo Tagged Parents',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged.parents',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.mondo_tagged.source_text',
    displayName: 'Participant Mondo Tagged Source Text',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.mondo_tagged.source_text',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.observed_phenotype_tagged',
    displayName: 'Participant Observed Phenotype Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.observed_phenotype_tagged.age_at_event',
    displayName: 'Participant Observed Phenotype Tagged Age At Event',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged.age_at_event',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.observed_phenotype_tagged.internal_phenotype_id',
    displayName: 'Participant Observed Phenotype Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged.internal_phenotype_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.observed_phenotype_tagged.is_leaf',
    displayName: 'Participant Observed Phenotype Tagged Is Leaf',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged.is_leaf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.observed_phenotype_tagged.is_tagged',
    displayName: 'Participant Observed Phenotype Tagged Is Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged.is_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.observed_phenotype_tagged.name',
    displayName: 'Participant Observed Phenotype Tagged Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.observed_phenotype_tagged.parents',
    displayName: 'Participant Observed Phenotype Tagged Parents',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged.parents',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.observed_phenotype_tagged.source_text',
    displayName: 'Participant Observed Phenotype Tagged Source Text',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotype_tagged.source_text',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.observed_phenotypes',
    displayName: 'Participant Observed Phenotypes',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotypes',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.observed_phenotypes.age_at_event',
    displayName: 'Participant Observed Phenotypes Age At Event',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotypes.age_at_event',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.observed_phenotypes.is_leaf',
    displayName: 'Participant Observed Phenotypes Is Leaf',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotypes.is_leaf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.observed_phenotypes.is_tagged',
    displayName: 'Participant Observed Phenotypes Is Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotypes.is_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.observed_phenotypes.name',
    displayName: 'Participant Observed Phenotypes Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotypes.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.observed_phenotypes.parents',
    displayName: 'Participant Observed Phenotypes Parents',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.observed_phenotypes.parents',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.participant_2_id',
    displayName: 'Participant Participant 2 Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.participant_2_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.participant_id',
    displayName: 'Participant Participant Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.participant_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.phenotypes_tagged',
    displayName: 'Participant Phenotypes Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.phenotypes_tagged.age_at_event',
    displayName: 'Participant Phenotypes Tagged Age At Event',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.age_at_event',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.phenotypes_tagged.internal_phenotype_id',
    displayName: 'Participant Phenotypes Tagged Internal Phenotype Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.internal_phenotype_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.phenotypes_tagged.is_leaf',
    displayName: 'Participant Phenotypes Tagged Is Leaf',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.is_leaf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.phenotypes_tagged.is_observed',
    displayName: 'Participant Phenotypes Tagged Is Observed',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.is_observed',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.phenotypes_tagged.is_tagged',
    displayName: 'Participant Phenotypes Tagged Is Tagged',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.is_tagged',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.phenotypes_tagged.name',
    displayName: 'Participant Phenotypes Tagged Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.phenotypes_tagged.parents',
    displayName: 'Participant Phenotypes Tagged Parents',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.parents',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.phenotypes_tagged.source_text',
    displayName: 'Participant Phenotypes Tagged Source Text',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.phenotypes_tagged.source_text',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.relationship_to_proband',
    displayName: 'Participant Relationship To Proband',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.relationship_to_proband',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.release_id',
    displayName: 'Participant Release Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.release_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.sex',
    displayName: 'Participant Sex',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.sex',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.study',
    displayName: 'Participant Study',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Biospecimen::extended::participant.study',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.study.study_code',
    displayName: 'Participant Study Study Code',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.study.study_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.study_code',
    displayName: 'Participant Study Code',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.study_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.study_id',
    displayName: 'Participant Study Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.study_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.submitter_participant_id',
    displayName: 'Participant Submitter Participant Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::participant.submitter_participant_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant.vital_status',
    displayName: 'Participant Vital Status',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::participant.vital_status',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'release_id',
    displayName: 'Release Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::release_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'sample_2_id',
    displayName: 'Sample 2 Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::sample_2_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'sample_id',
    displayName: 'Sample Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::sample_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'sample_type',
    displayName: 'Sample Type',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::sample_type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'security',
    displayName: 'Security',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::security',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study',
    displayName: 'Study',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Biospecimen::extended::study',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.contact',
    displayName: 'Study Contact',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Biospecimen::extended::study.contact',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.contact.type',
    displayName: 'Study Contact Type',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::study.contact.type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.contact.value',
    displayName: 'Study Contact Value',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::study.contact.value',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.data_access_codes',
    displayName: 'Study Data Access Codes',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Biospecimen::extended::study.data_access_codes',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.data_access_codes.access_limitations',
    displayName: 'Study Data Access Codes Access Limitations',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::study.data_access_codes.access_limitations',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.data_access_codes.access_requirements',
    displayName: 'Study Data Access Codes Access Requirements',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::study.data_access_codes.access_requirements',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.domain',
    displayName: 'Study Domain',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::study.domain',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.name',
    displayName: 'Study Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::study.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.population',
    displayName: 'Study Population',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::study.population',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study.study_code',
    displayName: 'Study Study Code',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::study.study_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_code',
    displayName: 'Study Code',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Biospecimen::extended::study_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_id',
    displayName: 'Study Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::study_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'submitter_biospecimen_id',
    displayName: 'Submitter Biospecimen Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::submitter_biospecimen_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'submitter_sample_id',
    displayName: 'Submitter Sample Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Biospecimen::extended::submitter_sample_id',
    primaryKey: false,
  },
];

export default extendedMapping;
