import AggregationsType, { NumericAggregationsType } from '@ferlab/next/lib/common/types/aggregationsType';

const extendedMapping = [
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'contact',
    displayName: 'Contact',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Study::extended::contact',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'contact.type',
    displayName: 'Contact Type',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::contact.type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'contact.value',
    displayName: 'Contact Value',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::contact.value',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'data_access_codes',
    displayName: 'Data Access Codes',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Study::extended::data_access_codes',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'data_access_codes.access_limitations',
    displayName: 'Data Access Codes Access Limitations',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::data_access_codes.access_limitations',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'data_access_codes.access_requirements',
    displayName: 'Data Access Codes Access Requirements',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::data_access_codes.access_requirements',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'data_categories',
    displayName: 'Data Categories',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Study::extended::data_categories',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'data_categories.data_category',
    displayName: 'Data Categories Data Category',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::data_categories.data_category',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'data_categories.participant_count',
    displayName: 'Data Categories Participant Count',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'integer',
    gqlId: 'cqdg::Study::extended::data_categories.participant_count',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'data_category',
    displayName: 'Data Category',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::data_category',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'data_types',
    displayName: 'Data Types',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Study::extended::data_types',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'data_types.data_type',
    displayName: 'Data Types Data Type',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::data_types.data_type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'data_types.participant_count',
    displayName: 'Data Types Participant Count',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'integer',
    gqlId: 'cqdg::Study::extended::data_types.participant_count',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'datasets',
    displayName: 'Datasets',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Study::extended::datasets',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'datasets.data_types',
    displayName: 'Datasets Data Types',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::datasets.data_types',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'datasets.description',
    displayName: 'Datasets Description',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::datasets.description',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'datasets.experimental_strategies',
    displayName: 'Datasets Experimental Strategies',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::datasets.experimental_strategies',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'datasets.file_count',
    displayName: 'Datasets File Count',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'integer',
    gqlId: 'cqdg::Study::extended::datasets.file_count',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'datasets.name',
    displayName: 'Datasets Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::datasets.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'datasets.participant_count',
    displayName: 'Datasets Participant Count',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'integer',
    gqlId: 'cqdg::Study::extended::datasets.participant_count',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'description',
    displayName: 'Description',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::description',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'domain',
    displayName: 'Domain',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::domain',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'experimental_strategies',
    displayName: 'Experimental Strategies',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Study::extended::experimental_strategies',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'experimental_strategies.experimental_strategy',
    displayName: 'Experimental Strategies Experimental Strategy',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::experimental_strategies.experimental_strategy',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'experimental_strategies.file_count',
    displayName: 'Experimental Strategies File Count',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'integer',
    gqlId: 'cqdg::Study::extended::experimental_strategies.file_count',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'family_count',
    displayName: 'Family Count',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'integer',
    gqlId: 'cqdg::Study::extended::family_count',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'family_data',
    displayName: 'Family Data',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Study::extended::family_data',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'file_count',
    displayName: 'File Count',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'integer',
    gqlId: 'cqdg::Study::extended::file_count',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'hpo_terms',
    displayName: 'Hpo Terms',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::hpo_terms',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'icd_terms',
    displayName: 'Icd Terms',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::icd_terms',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'internal_study_id',
    displayName: 'Internal Study Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Study::extended::internal_study_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'keyword',
    displayName: 'Keyword',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::keyword',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'mondo_terms',
    displayName: 'Mondo Terms',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::mondo_terms',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'name',
    displayName: 'Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'participant_count',
    displayName: 'Participant Count',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'integer',
    gqlId: 'cqdg::Study::extended::participant_count',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'population',
    displayName: 'Population',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::population',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'release_id',
    displayName: 'Release Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Study::extended::release_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'sample_count',
    displayName: 'Sample Count',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Study::extended::sample_count',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'security',
    displayName: 'Security',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::security',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'status',
    displayName: 'Status',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::status',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_code',
    displayName: 'Study Code',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::study_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_id',
    displayName: 'Study Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Study::extended::study_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_version',
    displayName: 'Study Version',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::study_version',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'data_collection_methods',
    displayName: 'Data Collection Methods',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::data_collection_methods',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_designs',
    displayName: 'Design',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::study_designs',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'restricted',
    displayName: 'Restricted',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::restricted',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_designs',
    displayName: 'Study Designs',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::study_designs',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'data_collection_methods',
    displayName: 'Data Collection Methods',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::data_collection_methods',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'expected_number_participants',
    displayName: 'Expected Number Participants',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::expected_number_participants',
    primaryKey: false,
  },

  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'expected_number_biospecimens',
    displayName: 'Expected Number Biospecimens',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::expected_number_biospecimens',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'expected_number_files',
    displayName: 'Expected Number Files',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::expected_number_files',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'restricted_number_participants',
    displayName: 'Restricted Number Participants',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::restricted_number_participants',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'restricted_number_biospecimens',
    displayName: 'Restricted Number Biospecimens',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::restricted_number_biospecimens',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'restricted_number_files',
    displayName: 'Restricted Number Files',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::restricted_number_files',
    primaryKey: false,
  },

  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'principal_investigators',
    displayName: 'Principal Investigators',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::principal_investigators',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'contact_names',
    displayName: 'Contact Names',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::contact_names',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'contact_extensions',
    displayName: 'Contact Extensions',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::contact_extensions',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'contact_institutions',
    displayName: 'Contact Institutions',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::contact_institutions',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'contact_emails',
    displayName: 'Contact Emails',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::contact_emails',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'telecom',
    displayName: 'Telecom',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::telecom',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'website',
    displayName: 'Website',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::website',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'funding_sources',
    displayName: 'Funding Sources',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::funding_sources',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'citation_statement',
    displayName: 'Citation Statement',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::citation_statement',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'selection_criteria',
    displayName: 'Selection Criteria',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::selection_criteria',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'expected_items',
    displayName: 'Expected Items',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::expected_items',
    primaryKey: false,
  },
  {
    field: 'programs.name_fr',
    displayName: 'Program Name FR',
    active: true,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::programs__name_fr',
    primaryKey: false,
  },
  {
    field: 'programs.name_en',
    displayName: 'Program Name EN',
    active: true,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Study::extended::programs__name_en',
    primaryKey: false,
  },
];

export default extendedMapping;
